### PR TITLE
improve vercel example to just use edge runtime

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Excited to see this profiling work for the major various platform. This PR simplifies the Vercel example to only deploy an edge function so that it is on par with the Deno example. It is based on the Hello World Edge Functions example available here: https://github.com/vercel/examples/tree/main/edge-api-routes/hello-world 

Would appreciate if you could rerun your benchmarking so Vercel's performance is accurately represented in your post. 

Thank you!

### CODE REVIEW

**Comment by leerob** [comment]
Hey, following up here - any movement?

**Review by ry — APPROVED** [review]
LGTM

**Comment by leerob** [comment]
Thank you! Excited to see the updated post 😄

**Comment by leerob** [comment]
I saw this still isn't updated - any news?

**Pull request merged**
